version: '3'

vars:
  VENV_NAME: cli

tasks:
  release:
    cmds:
      - bumpversion patch
      - pdm publish
      - git push
  devrel:
    cmds:
      - git add . && git commit -m "devrel" || true
      - bumpversion build
      - pdm publish
      - git push
  update:
    cmds:
      - pdm add keyring-proxy
  create_venv:
    cmds:
      - python -m venv ~/.local/share/venv/{{.VENV_NAME}}
    status:
      - test -f ~/.local/share/venv/{{.VENV_NAME}}/bin/python
  use_venv:
    deps:
      - create_venv
    cmds:
      - pdm use -i ~/.local/share/venv/{{.VENV_NAME}}/bin/python
    status:
      - test $(dirname $(dirname $(pdm info --python))) -ef ~/.local/share/venv/{{.VENV_NAME}}
  sync:
    deps:
      - use_venv
    cmds:
      - pdm sync --without tools --only-keep
  init:
    deps:
      - sync
    cmds:
      - pdm add -e ../py-keyring-proxy --dev