version: '3'

tasks:
  release:
    cmds:
      - git add . && git commit -m "Release"
      - bumpversion patch
      - pdm publish
      - git push
  update:
    cmds:
      - pdm add keyring-proxy

    