version: '3'

vars:
  VENV_NAME: cli
  VENV_STORE: ~/.local/share/venv
  VENV_DIR: "{{.VENV_STORE}}/{{.VENV_NAME}}"
  VENV_PYTHON: "{{.VENV_DIR}}/bin/python"
  DEPS: ["keyring-proxy"]

tasks:
  release:
    cmds:
      - bumpversion patch
      - pdm publish
      - git push
  devrel:
    cmds:
      - git add .
      - if git commit --dry-run --short; then git commit -m "devrel"; else echo nothing changed; fi
      - bumpversion build
      - pdm publish
      - git push
  update:
    cmds:
      - for: { var: DEPS }
        cmd: pdm add "{{.ITEM}}"
      - git add pdm.lock pyproject.toml
      - if git commit --dry-run --short; then git commit -m "Updated deps"; else echo nothing updated; fi
  create_venv:
    cmds:
      - python -m venv {{.VENV_DIR}}
    status:
      - test -f {{.VENV_PYTHON}}
  use_venv:
    deps:
      - create_venv
    cmds:
      - pdm use -i {{.VENV_PYTHON}}
    status:
      - test -f .pdm-python
      - test $(dirname $(dirname $(pdm info --python))) -ef {{.VENV_DIR}}
  sync:
    deps:
      - use_venv
    cmds:
      - pdm sync --without tools --only-keep
  init:
    deps:
      - sync
    cmds:
      - for: { var: DEPS }
        cmd: pdm add -e ../py-{{.ITEM}} --dev